@Restaurants.API_HostAddress = https://localhost:44378

GET https://localhost:44378/weatherforecast/
Accept: application/json

###
POST https://localhost:44378/rest/generate?numberOfGenerations=3
Accept: application/json
Content-Type: application/json

{
    "minTempratureC": 3,
    "maxTempratureC": 5 
}
###
GET https://localhost:44378/api/Test
###
GET https://localhost:44378/api/restaurants
